### ISSUE TITLE
Android Studio Render Problem

### ISSUE THREAD

**Issue by bthncll** [leonardocavagnis/MQTTClientSample_Android#2]
I cloned this MQTTClientSample_Android repo and I opened this with android studio. But I had got render problem in Layout. Fragment Connect, content main, activity main did not render. Fragment client layout had not problem and Fragment Client was rendered. 

![image](https://user-images.githubusercontent.com/60079043/144718044-c136cdcd-5efe-4d31-bbe8-627ac72d6250.png)

![image](https://user-images.githubusercontent.com/60079043/144718055-bdbbb004-25f5-4104-9ed9-98cf576e0d9f.png)

**Comment by leonardocavagnis** [comment]
Dear bthncll,
Thanks for interest in my project and for reporting this issue. 
What Android Studio version are you using?

**Comment by bthncll** [comment]
The problems fixed :D thanks
